package com.tms.audit.entity;

public enum AuditAction {
    CREATED,
    UPDATED,
    STATUS_CHANGED,
    MOVED,
    DEFECT_LINKED,
    DEFECT_UNLINKED,
    REQUIREMENT_LINKED,
    REQUIREMENT_UNLINKED,
    VERSION_CREATED,
    VERSION_RESTORED,
    DELETED,
    // 테스트런
    RESULT_RECORDED,
    COMPLETED,
    REOPENED,
    // 첨부파일
    ATTACHMENT_ADDED,
    ATTACHMENT_DELETED,
    // 설정 / 데이터 작업
    SETTING_CHANGED,
    IMPORTED,
    BACKUP_CREATED,
    BACKUP_RESTORED
}
